version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
